spring:
  application:
    name: micr-pay
  thymeleaf:
    cache: false
  redis:
    host: 192.168.200.130
    port: 6379
    password: 123456

server:
  port: 9000
  servlet:
    context-path: /pay


dubbo:
  registry:
    address: zookeeper://192.168.200.130:2181
  scan:
    base-packages: com.xie.pay
  consumer:
    check: false
    retries: 0
  config-center:
    timeout: 10000