spring:
  application:
    name: micr-task

dubbo:
  registry:
    address: zookeeper://192.168.200.130:2181
  scan:
    base-packages: com.xie.task
  consumer:
    check: false
    retries: 0
  config-center:
    timeout: 10000